package alex;

public enum ClaseLexica {
	INT, REAL, BOOL, TRUE, FALSE, ID, ASIG,
	NENTERO, EXPON, DEC, EXPRES, SEPAR,
	SUMA, RESTA, MUL, DIV, AND, OR, NOT, MEN, MAY, 
	MENEQ, MAYEQ, EQUIV, DIST, PAP, PCIE, PTOCOMA, IGUAL,
	IGN, EOF, CERO
}
