package tiny1;

public enum ClaseLexica {
	INT, REAL, BOOL, STRING, AND, OR, NOT, NULL, TRUE, FALSE, PROC, IF, THEN, ELSE,
	ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE,
	NL, VAR, TYPE, ID, NENTERO, NREAL, LITCAT, SEPARACION, SUMA, RESTA, MUL, DIV, MEN, MAY,
	MENEQ, MAYEQ, EQUIV, DIST, PAP, PCIE, PTOCOMA, IGUAL, COMA, PORC, CORAP, CORCIE, LLAP,
	LLCIE, PNTO, FLECHA, AMP, IGN, COM, EOF
}
