
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 24 13:14:43 CEST 2021
//----------------------------------------------------

package conCup.asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int SEPARACION = 36;
  public static final int LITCAD = 35;
  public static final int LLCIE = 56;
  public static final int RESTA = 38;
  public static final int INT = 2;
  public static final int PORC = 52;
  public static final int DELETE = 26;
  public static final int WRITE = 28;
  public static final int CORCIE = 54;
  public static final int NOT = 8;
  public static final int AND = 6;
  public static final int IGUAL = 50;
  public static final int NREAL = 34;
  public static final int RECORD = 21;
  public static final int LLAP = 55;
  public static final int TYPE = 31;
  public static final int OR = 7;
  public static final int BOOL = 4;
  public static final int NENTERO = 33;
  public static final int CALL = 20;
  public static final int DIV = 40;
  public static final int SUMA = 37;
  public static final int IF = 13;
  public static final int ID = 32;
  public static final int ENDWHILE = 19;
  public static final int PTOCOMA = 49;
  public static final int OF = 23;
  public static final int DIST = 46;
  public static final int EOF = 0;
  public static final int AMP = 59;
  public static final int PARRAY = 22;
  public static final int TRUE = 10;
  public static final int PCIE = 48;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int CORAP = 53;
  public static final int COMA = 51;
  public static final int MUL = 39;
  public static final int IGN = 60;
  public static final int PNTO = 57;
  public static final int NULL = 9;
  public static final int COM = 61;
  public static final int REAL = 3;
  public static final int PAP = 47;
  public static final int FLECHA = 58;
  public static final int ENDIF = 16;
  public static final int ELSE = 15;
  public static final int MEN = 41;
  public static final int NL = 29;
  public static final int READ = 27;
  public static final int WHILE = 17;
  public static final int EQUIV = 45;
  public static final int THEN = 14;
  public static final int MENEQ = 43;
  public static final int PROC = 12;
  public static final int STRING = 5;
  public static final int POINTER = 24;
  public static final int FALSE = 11;
  public static final int MAYEQ = 44;
  public static final int MAY = 42;
  public static final int VAR = 30;
  public static final int DO = 18;
}

